/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blascomatiasmartin_tp7;

import javax.swing.JOptionPane;

/**
 *
 * @author M
 */
public class VistaFormMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaFormMaterias
     */
    public VistaFormMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        materiaID = new javax.swing.JLabel();
        materiaNom = new javax.swing.JLabel();
        materiaAnio = new javax.swing.JLabel();
        jtMateria = new javax.swing.JTextField();
        jtNombreMat = new javax.swing.JTextField();
        jtAnioMat = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Formulario de Materias");

        materiaID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        materiaID.setText("CODIGO DE MATERIA: ");

        materiaNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        materiaNom.setText("NOMBRE DE LA MATERIA:");

        materiaAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        materiaAnio.setText("AÑO AL QUE PERTENECE: ");

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(materiaNom)
                                .addGap(36, 36, 36)
                                .addComponent(jtNombreMat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(materiaAnio)
                                .addGap(33, 33, 33)
                                .addComponent(jtAnioMat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(materiaID)
                                .addGap(49, 49, 49)
                                .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 291, Short.MAX_VALUE)
                        .addComponent(guardar)
                        .addGap(32, 32, 32))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaID)
                    .addComponent(jtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaNom)
                    .addComponent(jtNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaAnio)
                    .addComponent(jtAnioMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(guardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
        int codigoMat=Integer.parseInt(jtMateria.getText());
        String nombreMat = jtNombreMat.getText();
        int anioMateria = Integer.parseInt(jtAnioMat.getText());
        
        
        Materia m1 = new Materia(codigoMat, nombreMat, anioMateria);
        
        //guardo
        if(Menu.agregarMaterias1(m1)){
            
            JOptionPane.showMessageDialog(this,"Materia Agregada");
        }
        limpiar();
    }//GEN-LAST:event_guardarActionPerformed
    
    private void limpiar(){
        jtMateria.setText("");
        jtNombreMat.setText("");
        jtAnioMat.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtAnioMat;
    private javax.swing.JTextField jtMateria;
    private javax.swing.JTextField jtNombreMat;
    private javax.swing.JLabel materiaAnio;
    private javax.swing.JLabel materiaID;
    private javax.swing.JLabel materiaNom;
    // End of variables declaration//GEN-END:variables
}
